"""Add title and summary to documents and chunks

Revision ID: 2c454120dbc1
Revises: 252cc20ba730
Create Date: 2025-04-11 13:53:21.650451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c454120dbc1'
down_revision = '252cc20ba730'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('document_chunks', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary')
    op.drop_column('document_chunks', 'summary')
    op.drop_column('document_chunks', 'title')
    # ### end Alembic commands ###
