"""Add index on documents url column

Revision ID: b3157d50e29e
Revises: c6ca8e1a69e9
Create Date: 2025-04-11 16:00:39.221232

"""

from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3157d50e29e"
down_revision = "c6ca8e1a69e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_documents_url"), "documents", ["url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_url"), table_name="documents")
    # ### end Alembic commands ###
