"""Add markdown_content column to documents table

Revision ID: c6ca8e1a69e9
Revises: 2c454120dbc1
Create Date: 2025-04-11 14:45:24.216160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ca8e1a69e9'
down_revision = '2c454120dbc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('markdown_content', sa.Text(), nullable=True))
    op.create_table_comment(
        'documents',
        'Represents individual items (pages, files, records) retrieved from a data source, including cleaned content.',
        existing_comment='Represents individual items (pages, files, records) retrieved from a data source.',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'documents',
        'Represents individual items (pages, files, records) retrieved from a data source.',
        existing_comment='Represents individual items (pages, files, records) retrieved from a data source, including cleaned content.',
        schema=None
    )
    op.drop_column('documents', 'markdown_content')
    # ### end Alembic commands ###
